blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestBlogFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<slug:post>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestBlogFeed(), name='post_feed'),
    path('search/', views.blog_search, name='blog_search')
]

techBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'blogs': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

handler404 = 'blog.views.error_404'

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF',   'Draft'
        PUBLISHED = 'Pb', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f"comments on {self.post} by {self.name}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.postgres.search import SearchVector, SearchQuery

# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    # tags
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    # pagination with 5 post per page
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.get_page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post,
                             publish__year=year, publish__month=month, publish__day=day)

    # list of active comments
    comments = post.comments.filter(active=True)
    # form for user to add comments
    form = CommentForm()
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:3]

    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                f'{post.title}'
            message = f"Read {post.title} at {post_url}\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'tolu.adeyemo7@gmail.com', [cd['to']])
            sent = True
            # send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post):
    post = get_object_or_404(Post, slug=post, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # create a comment without saving it to the database
        comment = form.save(commit=False)
        # assign the comment to the current post
        comment.post = post
        # you can save the comment now😉
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def blog_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector(
                'title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})


def error_404(request, exception):
    return render(request, 'blog/404.html')

blog/templates/blog/base.html
{% load blog_tags %} {% load static %}
<!DOCTYPE html>
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>techBlog</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <script src="{% static 'js/script.js' %}" defer></script>
    <!-- favicon -->
    <link
      rel="icon"
      type="image/svg+xml"
      href="{% static 'images/favicon.svg' %}"
    />
    <link
      rel="icon"
      type="image/png"
      href="{% static 'images/favicon.png' %}"
    />
  </head>
  <body
    class="bg-light-background dark:bg-dark-background scrollbar-hide font-body"
  >
    <!-- nav -->
    <nav
      class="w-full flex justify-between items-center py-4 px-4 md:px-6 lg:px-8 mx-auto"
    >
      <!-- logo section -->
      <a href="{% url 'blog:post_list' %}" class="cursor-pointer">
        <p class="text-3xl font-bold text-stone-800 dark:text-stone-100">
          tech<span class="text-link">Blog</span>
        </p>
      </a>
      <!-- right -->
      <div class="flex items-center gap-x-4 md:gap-x-6">
        <!-- search -->
        <a
          href="{% url 'blog:blog_search' %}"
          title="search"
          class="cursor-pointer text-gray-800 dark:text-gray-100"
        >
          <svg
            viewBox="0 0 20 20"
            fill="currentColor"
            class="w-4 h-4 md:w-6 md:h-6"
          >
            <path
              fill-rule="evenodd"
              d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
              clip-rule="evenodd"
            />
          </svg>
        </a>
        <!-- dark mode toggle -->
        <div
          class="h-8 w-8 md:h-10 md:w-10 rounded-full flex items-center justify-center bg-gray-300 hover:bg-gray-400/75 cursor-pointer"
          onclick="darkModeToggle()"
        >
          <svg
            viewBox="0 0 20 20"
            fill="currentColor"
            class="w-4 h-4 md:h-6 md:w-6"
            id="icon"
          >
            <path
              fill-rule="evenodd"
              d="M7.455 2.004a.75.75 0 01.26.77 7 7 0 009.958 7.967.75.75 0 011.067.853A8.5 8.5 0 116.647 1.921a.75.75 0 01.808.083z"
              clip-rule="evenodd"
            />
          </svg>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}

    <!-- footer -->
    <footer
      class="flex flex-col items-center justify-center h-[25vh] border border-light-hover dark:border-dark-hover gap-y-4 mt-8"
    >
      <div class="w-max mx-auto flex items-center gap-x-1">
        <img
          src="{% static 'images/logo.png' %}"
          alt="logo"
          class="w-auto h-1/2 object-center object-contain"
        />
        <span class="text-light-text dark:text-dark-text text-sm font-bold"
          >tech<span class="text-link">Blog</span></span
        >
      </div>

      <p
        class="text-sm font-semibold text-light-textSec dark:text-dark-textSec"
      >
        &copy; <span id="currentYear"></span> techBlog.com. All rights reserved.
      </p>
    </footer>
  </body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
<p></p>
{% block title %} Add A Comment {% endblock title %} {% block content %}
<div>
  {% if comment %}
  <h2>Your comment has been added.</h2>
  <p>
    <a href="{{ post.get_absolute_url }}">Back to post</a>
  </p>
  {% else %}
  <div>{% include "blog/post/includes/comment_form.html" %}</div>
  {% endif %}
</div>
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %} {% load blog_tags %} {% block title %} {{ post.title }} {% endblock %}
{% block content %}
<main class="w-full md:w-5/6 lg:w-3/4 mx-auto grid grid-cols-1 lg:grid-cols-5 gap-y-8 p-4 lg:p-6 mt-4 md:mt-6">
  <!-- back -->
  <a href="{% url 'blog:post_list' %}" title="back home"
    class="w-8 h-8 md:w-10 md:h-10 border-[0.5px] border-light-textSubtle dark:border-dark-textSubtle rounded-full flex justify-center items-center bg-light-hover dark:bg-dark-hover text-light-text dark:text-dark-text lg:col-span-1">
    <svg viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 md:w-6 md:h-6">
      <path fill-rule="evenodd"
        d="M15 10a.75.75 0 01-.75.75H7.612l2.158 1.96a.75.75 0 11-1.04 1.08l-3.5-3.25a.75.75 0 010-1.08l3.5-3.25a.75.75 0 111.04 1.08L7.612 9.25h6.638A.75.75 0 0115 10z"
        clip-rule="evenodd" />
    </svg>
  </a>
  <!-- content -->
  <div class="grid grid-cols-1 gap-y-4 lg:col-span-3">
    <!-- author + share -->
    <div class="flex justify-between items-center">
      <div class="text-light-textSubtle dark:text-dark-textSubtle">
        <span>{{ post.author }}</span> | <span>{{ post.publish }}</span>
      </div>

      <!-- share -->
      <a href="{% url "blog:post_share" post.id %}" title="share">
        <span class="text-light-textSec dark:text-dark-textSec hover:text-light-text dark:hover:text-dark-text">
          <svg viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path
              d="M13 4.5a2.5 2.5 0 11.702 1.737L6.97 9.604a2.518 2.518 0 010 .792l6.733 3.367a2.5 2.5 0 11-.671 1.341l-6.733-3.367a2.5 2.5 0 110-3.475l6.733-3.366A2.52 2.52 0 0113 4.5z" />
          </svg>
        </span>
      </a>
    </div>

    <!-- article -->
    <div class="flex flex-col gap-y-6">
      <h1 class="text-3xl md:text-5xl lg:text-7xl font-bold text-light-text dark:text-dark-text w-full">
        {{ post.title }}
      </h1>
      <article class="flex flex-col gap-y-2 text-base text-light-textSec dark:text-dark-textSec">
        {{ post.body|markdown }}
      </article>
      <!-- tags -->
      <div class="flex gap-x-1.5">
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}" title="blog tag title"
          class="bg-light-hover dark:bg-dark-hover text-light-textSec dark:text-dark-textSec px-2 py-0.5 rounded-lg text-sm font-semibold font-sans capitalize">{{tag.name}}</a>
        {% if not forloop.last %},
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <!-- comments -->
    <div class="mt-4 flex flex-col gap-y-1">
      <h3 class="text-2xl md:text-3xl font-bold text-light-text dark:text-dark-text">
        Recent Comments
      </h3>
      {% with comments.count as total_comments %}
      <p class="text-lg font-medium text-light-textSec dark:text-dark-textSec">
        {{ total_comments }}
        <span class="font-normal text-base italic">comment{{ total_comments|pluralize }}</span>
      </p>
      {% endwith %}
    </div>

    <!-- commentList -->
    <div class="flex flex-col divide-y-2 divide-light-textSubtle dark:divide-dark-textSubtle w-full">
      {% for comment in comments %}
      <!-- commentItem -->
      <div class="flex flex-col gap-y-2 p-2 pb-4">
        <p class="text-light-text dark:text-dark-text text-sm font-medium">
          {{ comment.name }} <span class="font-normal"> | {{ comment.created }}</span>
        </p>
        <p class="text-light-textSec dark:text-dark-textSec text-base font-normal">
          {{ comment.body }}
        </p>
      </div>
      {% empty %}
      <p class="text-lg font-medium text-light-textSec dark:text-dark-textSec">There are no comments here.</p>
      {% endfor %}
    </div>

    <!-- addAComment -->
    <h3 class="mt-4 text-2xl md:text-3xl font-bold text-light-text dark:text-dark-text">
      Add a Comment
    </h3>
    
    {% include "blog/post/includes/comment_form.html" %}
  </div>
</main>
{% endblock content %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.slug %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add comment" />
</form> 

blog/templates/blog/post/latest_posts.html
<ul class="flex flex-col gap-y-4">
  {% for post in latest_blogs %}
  <li
    class="text-2xl font-medium text-light-textSec dark:text-dark-textSec hover:underline decoration-link hover:text-light-text dark:hover:text-dark-text"
  >
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %} {% load blog_tags %} {% block title %} techBlog {% endblock title %}
{% block content %}
{% if tag %} <main class="w-full h-20 md:h-24 bg-light-hover dark:bg-dark-hover my-4 md:my-8">
  <div class="flex justify-between items-center w-full px-2 md:px-0 md:w-5/6 lg:w-3/4 mx-auto h-full">
    <h3 class="text-lg md:text-xl font-medium text-light-text dark:text-dark-text">
      Posts tagged with "{{tag.name}}"
    </h3>
    <a href="{% url "blog:post_list" %}" class="text-link hover:text-linkHover text-sm">Home</a>
  </div>
</main>
{% endif %}
<main class="w-full mx-auto grid grid-cols-1 lg:grid-cols-3 gap-y-4 md:gap-x-4 p-2 md:p-4">
  <section class="md:col-span-2 w-full">
    <!-- blog list -->
    <div class="flex flex-col gap-y-6">
      {% for post in posts %}

      <div class="w-full grid grid-cols-1 md:grid-cols-7 gap-y-4 p-2">
        <!-- author and date -->
        <div class="md:col-span-2 text-sm font-normal text-light-textSubtle dark:text-dark-textSubtle">
          <span>{{ post.author }}</span> | <span>{{post.publish}}</span>
        </div>
        <!-- content -->
        <div
          class="md:col-span-5 flex flex-col gap-y-2 hover:bg-light-hover dark:hover:bg-dark-hover hover:cursor-pointer rounded-2xl p-2">
          <h3 class="capitalize text-xl md:text-3xl font-bold text-light-text dark:text-dark-text">
            {{ post.title }}
          </h3>
          <p class="text-base text-light-textSec dark:text-dark-textSec">
            {{ post.body|markdown|truncatewords:30 }}
          </p>
          <a href="{{ post.get_absolute_url }}" title="read more" class="text-sm font-medium text-link w-max">Read full
            blog</a>
          <!-- tags -->
          <div class="flex gap-x-1.5">
            {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}" title="blog tag title"
              class="bg-light-hover dark:bg-dark-hover text-light-textSec dark:text-dark-textSec px-2 py-0.5 rounded-lg text-sm font-semibold font-sans capitalize">{{tag.name}}</a>
            {% if not forloop.last %},
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <!-- sidebar -->
  <div
    class="md:col-span-1 h-max bg-light-hover dark:bg-dark-hover text-light-text dark:text-dark-text rounded-md p-3 flex flex-col gap-y-4">
    <!-- latest posts -->
    <div class="flex flex-col gap-y-6 p-2">
      <h3 class="text-3xl font-semibold text-light-text dark:text-dark-text">
        Latest Posts
      </h3>
      <!-- post list -->
      {% show_latest_blogs 5 %}
    </div>
    <!-- popular posts -->
    <div class="flex flex-col gap-y-6 p-2">
      <h3 class="text-3xl font-semibold text-light-text dark:text-dark-text">
        Trending Posts 🔥
      </h3>
      <!-- post list -->
      {% get_most_commented_blogs as most_commented_blogs %}
      <ul class="flex flex-col gap-y-4">
        {% for post in most_commented_blogs %}
        <!-- post list item -->
        <li
          class="text-2xl font-medium text-light-textSec dark:text-dark-textSec hover:underline decoration-link hover:text-light-text dark:hover:text-dark-text">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</main>
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
Searches for Blog Posts
{% endblock title %}
{% block content %}

<div>
  {% if query %}
  <div class="w-full h-20 md:h-24 bg-light-hover dark:bg-dark-hover my-4 md:my-8">
    <div class="flex justify-between items-center w-full px-2 md:px-0 md:w-5/6 lg:w-3/4 mx-auto h-full">
      <h3 class="text-lg md:text-xl font-medium text-light-text dark:text-dark-text">
        Search results for: "{{ query }}"
      </h3>
      <a href="{% url "blog:post_list" %}" class="text-link hover:text-linkHover text-sm">Home</a>
    </div>
  </div>

  <h4
    class="text-base md:text-lg font-normal text-light-textSec dark:text-dark-textSec w-full px-2 md:px-0 md:w-5/6 lg:w-3/4 mx-auto">
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}.
    {% endwith %}
  </h4>

  <!-- results list -->
  <div
    class="w-full px-2 md:px-0 md:w-5/6 lg:w-3/4 mx-auto grid grid-cols-1 divide-y-[1.5px] divide-light-textSubtle dark:divide-dark-textSubtle">
    {% for post in results %}

    <div
      class="flex flex-col gap-y-2 w-full group h-full hover:bg-light-hover dark:hover:bg-dark-hover p-4 cursor-pointer">
      <a href="{{ post.get_aboslute_url }}"
        class="text-lg md:text-xl font-bold text-light-textSec dark:text-dark-textSec group-hover:text-light-textSubtle group-hover:dark:text-dark-textSubtle">{{ post.title }}</a>
      <p
        class="text-sm font-light text-light-textSec dark:text-dark-textSec md:w-3/4 text-left group-hover:text-light-textSubtle group-hover:dark:text-dark-textSubtle">
        {{ post.body|markdown|truncatewords_html:15 }}
      </p>
    </div>
    {% empty %}
    <h4
      class="text-base md:text-lg font-normal text-light-textSec dark:text-dark-textSec w-full px-2 md:px-0 md:w-5/6 lg:w-3/4 mx-auto">
      No results were found for "{{query}}".
    </h4>
    {% endfor %}
  </div>
  <p>
    <a href="{% url "blog:blog_search" %}">Search again</a>
  </p>
  {% else %}
  <main class="mt-6 w-full px-2 md:w-5/6 lg:w-3/4 mx-auto">
    <!-- search form -->
    <form method="get" class="w-full">
      {% csrf_token %}
      <div class="flex flex-col gap-y-2 w-full relative">
        <label for="search" class="order-last text-base text-light-textSec dark:text-dark-textSec ml-2">Quick Search
          <span class="text-light-textSubtle dark:text-dark-textSubtle font-bold ml-1">Ctrl /</span></label>
        <input type="search" name="query" id="search" placeholder="type then hit enter to search"
          class="w-full h-20 placeholder:uppercase placeholder:text-light-textSubtle dark:placeholder:text-dark-textSubtle placeholder:text-base pl-14 bg-transparent dark:bg-transparent border-2 border-light-textSubtle dark:border-dark-textSubtle text-light-textSec dark:text-dark-textSec focus:bg-light-hover dark:bg-dark-hover focus:outline-none focus:border-link focus:ring-2 focus:ring-link focus:border-none" />
        <span
          class="hidden absolute top-7 right-4 z-20 text-light-textSec dark:text-dark-textSec bg-light-hover dark:bg-dark-hover p-1 px-2 rounded text-xs cursor-pointer"
          id="esc">Esc</span>
        <span class="absolute top-7 left-4 text-light-text dark:text-dark-text"><svg viewBox="0 0 20 20"
            fill="currentColor" class="w-6 h-6">
            <path fill-rule="evenodd"
              d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
              clip-rule="evenodd" />
          </svg>
        </span>
      </div>
      <div class="hidden">
        <button type="submit" id="submit-button" class="hidden">
          search
        </button>
      </div>
    </form>
  </main>
  {% endif %}
</div>
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %} {% block title %} Share a post {% endblock %}
<div></div>
{% block content %}
<a href="{% url 'blog:post_list' %}">Back</a>
<div>
  {% if sent %}
  <h1>Post shared successfully</h1>
  <p>
    "{{ post.title }}" has been shared successfully to
    <span>{{ form.cleaned_data.to}}</span>"
  </p>
  {% else %}
  <h1>Share "{{ post.title }}" by email</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Share" />
  </form>
  {% endif %}
</div>
{% endblock %}

blog/templates/pagination.html
<!-- pagination -->
<div
  class="w-full flex flex-col md:flex-row gap-y-3 justify-between md:items-center px-4 py-2 dark:text-dark-textSec text-light-textSec text-sm mx-auto"
>
  <!-- pages -->
  <p class="font-medium">
    Page {{ page.number }} of {{ page.paginator.num_pages }}
  </p>
  <!-- buttons -->
  <div class="flex items-center gap-x-4">
    {% if page.has_previous %}
    <a
      href="?page={{ page.previous_page_number }}"
      class="rounded-md border border-light-textSec dark:border-dark-textSec dark:hover:bg-dark-hover hover:bg-light-hover dark:hover:text-dark-text hover:text-light-text hover:border-none font-medium px-4 py-2"
      >Previous</a
    >
    {% endif %} {% if page.has_next %}
    <a
      href="?page={{ page.next_page_number }}"
      class="rounded-md border border-light-textSec dark:border-dark-textSec dark:hover:bg-dark-hover hover:bg-light-hover dark:hover:text-dark-text hover:text-light-text hover:border-none font-medium px-4 py-2"
      >Next</a
    >
    {% endif %}
  </div>
</div>